import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useState } from "react";
import { Autocomplete } from "@mantine/core";
import { ActionIcon, useMantineColorScheme } from "@mantine/core";
import { Drawer, Button, Group } from "@mantine/core";
import Link from "next/link";
import { Sun, MoonStars } from "tabler-icons-react";

export default function Home() {
  const { colorScheme, toggleColorScheme } = useMantineColorScheme();
  const dark = colorScheme === "dark";

  const [opened, setOpened] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className="max-w-3xl mx-auto w-full">
          <div className="my-10">
            <ActionIcon
              variant="outline"
              color={dark ? "yellow" : "blue"}
              onClick={() => toggleColorScheme()}
              title="Toggle color scheme"
            >
              {dark ? <Sun size={18} /> : <MoonStars size={18} />}
            </ActionIcon>
            <div className="space-x-5 my-10">
              <Button
                variant="gradient"
                gradient={{ from: "indigo", to: "cyan" }}
              >
                Indigo cyan
              </Button>
              <Button
                variant="gradient"
                gradient={{ from: "teal", to: "lime", deg: 105 }}
              >
                Lime green
              </Button>
              <Button
                variant="gradient"
                gradient={{ from: "teal", to: "blue", deg: 60 }}
              >
                Teal blue
              </Button>
              <Button
                variant="gradient"
                gradient={{ from: "orange", to: "red" }}
              >
                Orange red
              </Button>
              <Button
                variant="gradient"
                gradient={{ from: "#ed6ea0", to: "#ec8c69", deg: 35 }}
              >
                Peach
              </Button>
            </div>
          </div>
          <Autocomplete
            label="Your favorite framework/library"
            placeholder="Pick one"
            className="max-w-lg"
            data={["React", "Angular", "Svelte", "Vue"]}
          />
          <div className="my-10">
            <Drawer
              opened={opened}
              onClose={() => setOpened(false)}
              title="Select your favourite lib"
              padding="xl"
              size="xl"
            >
              <Autocomplete
                label="Your favorite framework/library"
                placeholder="Pick one"
                data={["React", "Angular", "Svelte", "Vue"]}
              />
            </Drawer>

            <Group position="center">
              <Button onClick={() => setOpened(true)}>Open Drawer</Button>
            </Group>
            <div className="mt-10">
              <Link href="/dash">Hello world</Link>
            </div>
          </div>
        </div>

        <p className="text-3xl font-bold underline">
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
